import { Injectable } from '@angular/core';

export interface IconTranslation {
  glyphicon: string;
  fontAwesome: string | null;
}

@Injectable({
  providedIn: 'root'
})
export class IconTranslateService {

  private readonly iconMap: IconTranslation[] = [

    // Core
    { glyphicon: 'asterisk', fontAwesome: 'asterisk' },
    { glyphicon: 'plus', fontAwesome: 'plus' },
    { glyphicon: 'euro', fontAwesome: 'euro-sign' },
    { glyphicon: 'minus', fontAwesome: 'minus' },
    { glyphicon: 'cloud', fontAwesome: 'cloud' },
    { glyphicon: 'envelope', fontAwesome: 'envelope' },
    { glyphicon: 'pencil', fontAwesome: 'pencil' },
    { glyphicon: 'glass', fontAwesome: 'martini-glass' },
    { glyphicon: 'music', fontAwesome: 'music' },
    { glyphicon: 'search', fontAwesome: 'magnifying-glass' },
    { glyphicon: 'heart', fontAwesome: 'heart' },
    { glyphicon: 'star', fontAwesome: 'star' },
    { glyphicon: 'user', fontAwesome: 'user' },
    { glyphicon: 'film', fontAwesome: 'film' },
    { glyphicon: 'th-large', fontAwesome: 'table-cells-large' },
    { glyphicon: 'th', fontAwesome: 'table-cells' },
    { glyphicon: 'th-list', fontAwesome: 'list' },
    { glyphicon: 'ok', fontAwesome: 'check' },
    { glyphicon: 'remove', fontAwesome: 'xmark' },
    { glyphicon: 'zoom-in', fontAwesome: 'magnifying-glass-plus' },
    { glyphicon: 'zoom-out', fontAwesome: 'magnifying-glass-minus' },
    { glyphicon: 'off', fontAwesome: 'power-ogff' },
    { glyphicon: 'signal', fontAwesome: 'signal' },
    { glyphicon: 'cog', fontAwesome: 'gear' },
    { glyphicon: 'trash', fontAwesome: 'trash-can' },

    // Navigation
    { glyphicon: 'home', fontAwesome: 'house' },
    { glyphicon: 'file', fontAwesome: 'file' },
    { glyphicon: 'time', fontAwesome: 'clock' },
    { glyphicon: 'road', fontAwesome: 'road' },
    { glyphicon: 'download-alt', fontAwesome: null },
    { glyphicon: 'download', fontAwesome: null },
    { glyphicon: 'upload', fontAwesome: null },
    { glyphicon: 'inbox', fontAwesome: null },
    { glyphicon: 'play-circle', fontAwesome: null },
    { glyphicon: 'repeat', fontAwesome: null },
    { glyphicon: 'refresh', fontAwesome: null },
    { glyphicon: 'list-alt', fontAwesome: null },
    { glyphicon: 'lock', fontAwesome: null },
    { glyphicon: 'flag', fontAwesome: 'flag' },
    { glyphicon: 'headphones', fontAwesome: null },
    { glyphicon: 'volume-off', fontAwesome: null },
    { glyphicon: 'volume-down', fontAwesome: null },
    { glyphicon: 'volume-up', fontAwesome: null },
    { glyphicon: 'qrcode', fontAwesome: null },
    { glyphicon: 'barcode', fontAwesome: null },
    { glyphicon: 'tag', fontAwesome: null },
    { glyphicon: 'tags', fontAwesome: null },
    { glyphicon: 'book', fontAwesome: 'book' },
    { glyphicon: 'bookmark', fontAwesome: null },
    { glyphicon: 'print', fontAwesome: null },
    { glyphicon: 'camera', fontAwesome: null },
    { glyphicon: 'font', fontAwesome: null },
    { glyphicon: 'bold', fontAwesome: null },
    { glyphicon: 'italic', fontAwesome: null },
    { glyphicon: 'text-height', fontAwesome: null },
    { glyphicon: 'text-width', fontAwesome: null },
    { glyphicon: 'align-left', fontAwesome: null },
    { glyphicon: 'align-center', fontAwesome: null },
    { glyphicon: 'align-right', fontAwesome: null },
    { glyphicon: 'align-justify', fontAwesome: null },
    { glyphicon: 'list', fontAwesome: null },
    { glyphicon: 'indent-left', fontAwesome: null },
    { glyphicon: 'indent-right', fontAwesome: null },
    { glyphicon: 'facetime-video', fontAwesome: null },
    { glyphicon: 'picture', fontAwesome: null },

    // Medien / Status
    { glyphicon: 'map-marker', fontAwesome: 'location-dot' },
    { glyphicon: 'adjust', fontAwesome: 'circle-half-stroke' },
    { glyphicon: 'tint', fontAwesome: 'droplet' },
    { glyphicon: 'edit', fontAwesome: 'pen-to-square' },
    { glyphicon: 'share', fontAwesome: 'share-from-square' },
    { glyphicon: 'check', fontAwesome: 'square-checl' },
    { glyphicon: 'move', fontAwesome: 'arrows-up-down-left-right' },
    { glyphicon: 'step-backward', fontAwesome: 'backward-step' },
    { glyphicon: 'fast-backward', fontAwesome: 'forward-step' },
    { glyphicon: 'backward', fontAwesome: 'backward' },
    { glyphicon: 'play', fontAwesome: 'play' },
    { glyphicon: 'pause', fontAwesome: 'pause' },
    { glyphicon: 'stop', fontAwesome: 'stop' },
    { glyphicon: 'forward', fontAwesome: 'forward' },
    { glyphicon: 'fast-forward', fontAwesome: null },
    { glyphicon: 'step-forward', fontAwesome: null },
    { glyphicon: 'eject', fontAwesome: null },
    { glyphicon: 'chevron-left', fontAwesome: null },
    { glyphicon: 'chevron-right', fontAwesome: null },
    { glyphicon: 'plus-sign', fontAwesome: 'circle-plus' },
    { glyphicon: 'minus-sign', fontAwesome: null },
    { glyphicon: 'remove-sign', fontAwesome: null },
    { glyphicon: 'ok-sign', fontAwesome: null },
    { glyphicon: 'question-sign', fontAwesome: null },
    { glyphicon: 'info-sign', fontAwesome: null },
    { glyphicon: 'screenshot', fontAwesome: null },
    { glyphicon: 'remove-circle', fontAwesome: null },
    { glyphicon: 'ok-circle', fontAwesome: null },
    { glyphicon: 'ban-circle', fontAwesome: null },

    // Pfeile / Sonstiges
    { glyphicon: 'arrow-left', fontAwesome: null },
    { glyphicon: 'arrow-right', fontAwesome: null },
    { glyphicon: 'arrow-up', fontAwesome: null },
    { glyphicon: 'arrow-down', fontAwesome: null },
    { glyphicon: 'share-alt', fontAwesome: null },
    { glyphicon: 'resize-full', fontAwesome: null },
    { glyphicon: 'resize-small', fontAwesome: null },
    { glyphicon: 'exclamation-sign', fontAwesome: null },
    { glyphicon: 'gift', fontAwesome: null },
    { glyphicon: 'leaf', fontAwesome: 'leaf' },
    { glyphicon: 'fire', fontAwesome: null },
    { glyphicon: 'eye-open', fontAwesome: 'eye' },
    { glyphicon: 'eye-close', fontAwesome: 'eye-slash' },
    { glyphicon: 'warning-sign', fontAwesome: 'triangle-exclamation' },
    { glyphicon: 'plane', fontAwesome: 'plane-up' },
    { glyphicon: 'calendar', fontAwesome: null },
    { glyphicon: 'random', fontAwesome: null },
    { glyphicon: 'comment', fontAwesome: null },
    { glyphicon: 'magnet', fontAwesome: null },
    { glyphicon: 'chevron-up', fontAwesome: null },
    { glyphicon: 'chevron-down', fontAwesome: null },
    { glyphicon: 'retweet', fontAwesome: null },
    { glyphicon: 'shopping-cart', fontAwesome: 'cart-shopping' },
    { glyphicon: 'folder-close', fontAwesome: null },
    { glyphicon: 'folder-open', fontAwesome: null },
    { glyphicon: 'resize-vertical', fontAwesome: null },
    { glyphicon: 'resize-horizontal', fontAwesome: null },

    // Extended
    { glyphicon: 'hdd', fontAwesome: null },
    { glyphicon: 'bullhorn', fontAwesome: null },
    { glyphicon: 'bell', fontAwesome: null },
    { glyphicon: 'certificate', fontAwesome: null },
    { glyphicon: 'thumbs-up', fontAwesome: null },
    { glyphicon: 'thumbs-down', fontAwesome: null },
    { glyphicon: 'hand-right', fontAwesome: null },
    { glyphicon: 'hand-left', fontAwesome: null },
    { glyphicon: 'hand-up', fontAwesome: null },
    { glyphicon: 'hand-down', fontAwesome: null },
    { glyphicon: 'circle-arrow-right', fontAwesome: null },
    { glyphicon: 'circle-arrow-left', fontAwesome: null },
    { glyphicon: 'circle-arrow-up', fontAwesome: null },
    { glyphicon: 'circle-arrow-down', fontAwesome: null },
    { glyphicon: 'globe', fontAwesome: null },
    { glyphicon: 'wrench', fontAwesome: null },
    { glyphicon: 'tasks', fontAwesome: null },
    { glyphicon: 'filter', fontAwesome: null },
    { glyphicon: 'briefcase', fontAwesome: null },
    { glyphicon: 'fullscreen', fontAwesome: null },
    { glyphicon: 'dashboard', fontAwesome: null },
    { glyphicon: 'paperclip', fontAwesome: null },
    { glyphicon: 'heart-empty', fontAwesome: 'heart' },
    { glyphicon: 'link', fontAwesome: null },
    { glyphicon: 'phone', fontAwesome: null },
    { glyphicon: 'pushpin', fontAwesome: null },
    { glyphicon: 'usd', fontAwesome: null },
    { glyphicon: 'gbp', fontAwesome: null },
    { glyphicon: 'sort', fontAwesome: null },
    { glyphicon: 'sort-by-alphabet', fontAwesome: null },
    { glyphicon: 'sort-by-alphabet-alt', fontAwesome: null },
    { glyphicon: 'sort-by-order', fontAwesome: null },
    { glyphicon: 'sort-by-order-alt', fontAwesome: null },
    { glyphicon: 'sort-by-attributes', fontAwesome: null },
    { glyphicon: 'sort-by-attributes-alt', fontAwesome: null },
    { glyphicon: 'unchecked', fontAwesome: null },
    { glyphicon: 'expand', fontAwesome: null },
    { glyphicon: 'collapse-down', fontAwesome: null },
    { glyphicon: 'collapse-up', fontAwesome: null },
    { glyphicon: 'log-in', fontAwesome: null },
    { glyphicon: 'flash', fontAwesome: null },
    { glyphicon: 'log-out', fontAwesome: null },
    { glyphicon: 'new-window', fontAwesome: null },
    { glyphicon: 'record', fontAwesome: 'record-vinyl' },
    { glyphicon: 'save', fontAwesome: null },
    { glyphicon: 'open', fontAwesome: null },
    { glyphicon: 'saved', fontAwesome: null },
    { glyphicon: 'import', fontAwesome: null },
    { glyphicon: 'export', fontAwesome: null },
    { glyphicon: 'send', fontAwesome: 'paper-plane' },
    { glyphicon: 'floppy-disk', fontAwesome: null },
    { glyphicon: 'floppy-saved', fontAwesome: null },
    { glyphicon: 'floppy-remove', fontAwesome: null },
    { glyphicon: 'floppy-save', fontAwesome: null },
    { glyphicon: 'floppy-open', fontAwesome: null },
    { glyphicon: 'credit-card', fontAwesome: null },
    { glyphicon: 'transfer', fontAwesome: null },
    { glyphicon: 'cutlery', fontAwesome: null },
    { glyphicon: 'header', fontAwesome: null },
    { glyphicon: 'compressed', fontAwesome: null },
    { glyphicon: 'earphone', fontAwesome: null },
    { glyphicon: 'phone-alt', fontAwesome: null },
    { glyphicon: 'tower', fontAwesome: null },
    { glyphicon: 'stats', fontAwesome: null },
    { glyphicon: 'sd-video', fontAwesome: null },
    { glyphicon: 'hd-video', fontAwesome: null },
    { glyphicon: 'subtitles', fontAwesome: null },
    { glyphicon: 'sound-stereo', fontAwesome: null },
    { glyphicon: 'sound-dolby', fontAwesome: null },
    { glyphicon: 'sound-5-1', fontAwesome: null },
    { glyphicon: 'sound-6-1', fontAwesome: null },
    { glyphicon: 'sound-7-1', fontAwesome: null },
    { glyphicon: 'copyright-mark', fontAwesome: null },
    { glyphicon: 'registration-mark', fontAwesome: null },
    { glyphicon: 'cloud-download', fontAwesome: null },
    { glyphicon: 'cloud-upload', fontAwesome: null },
    { glyphicon: 'tree-conifer', fontAwesome: 'tree' },
    { glyphicon: 'tree-deciduous', fontAwesome: 'tree' },
    { glyphicon: 'education', fontAwesome: 'graduation-cap' },
    { glyphicon: 'thumbtack', fontAwesome: 'thumbtack' },
    { glyphicon: 'blackboard', fontAwesome: 'chalkboard' },
    { glyphicon: 'bed', fontAwesome: 'bed' },
    { glyphicon: 'tent', fontAwesome: 'campground' },
    { glyphicon: 'ice', fontAwesome: 'ice-cream' }
    
  ];

  translate(glyphicon: string): string {
    const normalized = glyphicon?.toLowerCase();

    const match = this.iconMap.find(
      i => i.glyphicon === normalized
    );

    return match?.fontAwesome ?? this.getFallback(glyphicon);
  }

  private getFallback(glyphicon): string {
    console.log('missing glyphicon-icon: '+ glyphicon);
    return 'question-circle';
  }
}
