angular.module('kommonitorAdmin', ['kommonitorDataExchange', 'adminDashboardManagement', 'adminRoleManagement', 'adminTopicsManagement',
'adminSpatialUnitsManagement','adminIndicatorsManagement', 'adminGeoresourcesManagement', 'adminScriptManagement', 'adminScriptExecution',
'spatialUnitAddModal','spatialUnitEditMetadataModal', 'spatialUnitEditFeaturesModal','spatialUnitDeleteModal',
'georesourceDeleteModal','georesourceAddModal', 'georesourceEditFeaturesModal', 'georesourceEditMetadataModal', 'georesourceBatchUpdateModal',
'indicatorDeleteModal','indicatorAddModal', 'indicatorEditFeaturesModal', 'indicatorEditMetadataModal', 'indicatorBatchUpdateModal',
'batchUpdateResultModal', 'indicatorEditTimeseriesMapping',
'indicatorEditIndicatorSpatialUnitRolesModal', 
'topicEditModal', 'topicDeleteModal',
'scriptAddModal', "scriptDeleteModal",
'adminAppConfig', 'adminKeycloakConfig', 'adminControlsConfig', 'adminFilterConfig',
'roleAddModal', 'roleEditMetadataModal', 'roleDeleteModal',
'adminRoleExplanation',
// ,'spatialUnitDeleteModal',
]);
