import { reportingData } from './../reporting-modal.component';
import { CommonModule } from '@angular/common';
import { Component, EventEmitter, Input, OnInit, Output } from '@angular/core';
import { ReportingTemplateFilter } from 'pipes/reporting-template-filter.pipe';
import { FormsModule } from '@angular/forms';
import { SafeHtmlPipe } from 'pipes/safe-html.pipe';
import { NgbAccordionBody, NgbAccordionModule, NgbDatepickerModule } from '@ng-bootstrap/ng-bootstrap';
import { ReportingService, WorkflowState } from 'services/reporting-service/reporting.service';

@Component({
  selector: 'app-template-select',
  standalone: true,
  templateUrl: './template-select.component.html',
  styleUrls: ['./template-select.component.scss'],
  imports: [CommonModule, ReportingTemplateFilter, FormsModule, SafeHtmlPipe, NgbDatepickerModule, NgbAccordionModule]
})
export class TemplateSelectComponent implements OnInit {

  datePickerDate!: any;

  workflowState = WorkflowState;

  constructor(
    protected reportingService: ReportingService
  ) {}

  //prevent bootrap modals tabs opened by a tag with href elements from adding their anchor location to 
  // URL
 /*  $("a[href^='#']").click(function(e) {
          e.preventDefault();
          
  }) */

  ngOnInit(): void {

       // todo
  /*   this.datePicker = $('#reporting-general-settings-datefield').datepicker({
      autoclose: true,
      language: 'de',
      format: 'yyyy-mm-dd'
    });
    document.getElementById("reporting-load-commune-logo-button").addEventListener('change', readSingleFile, false); */   
  }

  onChangeDatepickerDate() {
    this.reportingService.generalSettings.creationDate = `${this.datePickerDate.year}-${this.datePickerDate.month}-${this.datePickerDate.day}`;
  }

  getPageNumber(index) {

    let pageNumber = 1;
    for(let i = 0; i < index; i ++) {
      if (this.showThisPage(this.reportingService.selectedTemplate.pages[i])) {
        pageNumber ++;
      }
    }
    return pageNumber;
  }

  showThisPage(page) {
    let pageWillBeShown = false;
    for(let visiblePage of this.filterPagesToShow()){
      if(visiblePage == page) {
        pageWillBeShown = true;
      }
    }
    return pageWillBeShown;
  }

  filterPagesToShow() {
    let pagesToShow:any[] = [];
    let skipNextPage = false;
    for (let i = 0; i < this.reportingService.selectedTemplate.pages.length; i ++) {
      let page = this.reportingService.selectedTemplate.pages[i];
      if (this.pageContainsDatatable(i)) {
        pagesToShow.push(page);
        skipNextPage = false;
      }
      else {
        if(skipNextPage == false) {
          pagesToShow.push(page);
          skipNextPage = true;
        }
        else {
          skipNextPage = false;
        }
      }
    }
    return pagesToShow;
  }

  pageContainsDatatable(pageID) {
    let page = this.reportingService.selectedTemplate.pages[pageID];
    let pageContainsDatatable = false;
    for(let pageElement of page.pageElements) {
      if(pageElement.type == "datatable") {
        pageContainsDatatable = true;
      }
    }
    return pageContainsDatatable;
  }
  

  /**
   * filters templates to only show the ones matching the given category.
   * @param {*} categoryId 
   * @returns 
   */
  templateFilter(categoryId) {
    return function(value) {
      return categoryId === value.categoryId;
    }
  }

  onTemplateElementClicked($event, templateId) {
    let el = $event.target;
    el.style.backgroundColor = "#0078D7";
    el.style.color = "white";
    document.querySelectorAll(".reporting-selectable-template").forEach( (element:any) => {
      if( el !== element) {
        element.style.backgroundColor = "white";
        element.style.color = "black";
      }
    });
    
    this.reportingService.changeSelectedTemplate(templateId);
  }

  templateSupportsFreeText() {
    if(!this.reportingService.selectedTemplate)
      return false;

    if(!this.reportingService.selectedTemplate.pages) {
      return false;
    }

    for(let page of this.reportingService.selectedTemplate.pages) {
      for(let pageElement of page.pageElements) {
        if (pageElement.type === "textInput") {
          return true;
        }
      }
    }
    return false;
  }

  onTemplateSelected() {

    this.reportingService.changeWorkflowState(this.workflowState.reportingOverview);

    // update selected template with general settings
 /*    for(let [idx, page] of this.reportingService.selectedTemplate.pages.entries()) {
      for(let el of page.pageElements) {
        if(el.type.includes("footerCreationInfo-")) {
          el.text = "Erstellt am " + this.reportingService.generalSettings.creationDate + " von " + this.reportingService.generalSettings.creator + ", " + this.reportingService.generalSettings.commune
        }
        if(el.type === "textInput") {
          el.text = this.reportingService.generalSettings.freeText;
        }

        // page number is generated by html expression, but we update if anyway for consistency
        if(el.type.includes("pageNumber-")) {
          el.placeholderText = "Seite " + this.getPageNumber(idx)
        }
      }
    } 

    this.data.reportingConfig.template = this.reportingService.selectedTemplate;
    this.data.reportingConfig.backupTemplate = JSON.stringify(this.reportingService.selectedTemplate);
    */
  }
  
  copy(obj) {
    var cp = {};
    for (var o in obj) {
        cp[o] = obj[o];
    }
    return cp;
  }

  onBackToWorkflowSelectionClicked() {
    this.reportingService.changeSelectedTemplate(0);
    this.reportingService.changeWorkflowState(this.workflowState.workflowSelect);
  }

}
